### PR TITLE
Hefty contrib PR

### PR DESCRIPTION
**Pull request by Twipped**
There's a lot in this PR, and honestly I don't expect anyone to merge it, but I wanted to do SOMETHING with this.

This PR incorporates the work by @socialatm on his branch, as well as work I put in. It bumps jsonld and jsonld-signatures to their current versions, updates various tests, switches from callbacks to promises, and solves a bunch of small bugs that were revealed when I added a low-interference eslint config.

It also raises the minimum node version to 16.

### CODE REVIEW

**Comment by evanp** [comment]
HFS! @socialatm and @Twipped would you like to join this project? Let's get it re-started and get a modern version into NPM.

**Comment by evanp** [comment]
And yes, I haven't been paying attention this project for years.

**Comment by evanp** [comment]
So, the unit tests fail. I see "should handle languages properly" and "should create a signed entry and verify it". Any idea what's happening there?

**Comment by socialatm** [comment]
@evanp I'll be happy to join and test/develop as time allows. Thanks

**Pull request merged**
